# fly.toml file generated for vite-starter on 2023-05-18T15:37:10-04:00

app = "vlcn-live-examples"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true
  
[mounts]
  destination = "/app/dbs"
  source = "dbs"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
